### PR TITLE
Pass in len(values) to get_window_bounds & fix existing flake8/black errors

### PR DESCRIPTION
**Pull request by mroeschke**
xref https://github.com/twosigma/pandas/pull/5#discussion_r309916743

`len(values)` is the only component required for `get_window_bounds` in `VariableWindowIndexer` and `FixedWindowIndexer` and is less complex than having the method accept `values` directly.

Also address some black and flake8 errors discovered by azure

### CODE REVIEW

**Review by jreback — CHANGES_REQUESTED** [review]
we will need to modify tests for this i think

**Comment by mroeschke** [comment]
The current tests I have added don't hit this case. Moreover, this aligns how the current Indexers utilize `values` i.e. `num_values` is passed instead of `values`

**Comment by jreback** [comment]
great so rebase this and good?

**Comment by mroeschke** [comment]
The last of the linting errors are related to files this project isn't touching, and the 3.7 builds seems to be an unrelated failure.

Odd the linting errors are not showing up in pandas/master

```
Linting code-blocks in .rst documentation
##[error]doc/source/getting_started/basics.rst(765,8): error F821: undefined name 'f'
##[error]doc/source/getting_started/basics.rst(765,10): error F821: undefined name 'g'
##[error]doc/source/getting_started/basics.rst(765,12): error F821: undefined name 'h'
##[error]doc/source/getting_started/basics.rst(771,17): error F821: undefined name 'h'
##[error]doc/source/getting_started/basics.rst(772,17): error F821: undefined name 'g'
##[error]doc/source/getting_started/basics.rst(773,17): error F821: undefined name 'f'
##[error]doc/source/development/contributing_docstring.rst(50,9): error F821: undefined name 'add'
##[error]doc/source/development/contributing_docstring.rst(52,9): error F821: undefined name 'add'
##[error]doc/source/development/contributing_docstring.rst(54,9): error F821: undefined name 'add'
##[error]doc/source/development/contributing_docstring.rst(190,5): error F811: redefinition of unused 'astype' from line 37
##[error]doc/source/development/contributing_docstring.rst(200,5): error F811: redefinition of unused 'astype' from line 44
##[error]doc/source/development/contributing_docstring.rst(210,5): error F811: redefinition of unused 'astype' from line 51
##[error]doc/source/development/contributing_docstring.rst(220,5): error F811: redefinition of unused 'astype' from line 58
##[error]doc/source/development/contributing_docstring.rst(325,5): error F811: redefinition of unused 'Series' from line 86
##[error]doc/source/development/contributing_docstring.rst(563,5): error F811: redefinition of unused 'Series' from line 105
##[error]doc/source/development/contributing_docstring.rst(914,5): error F811: redefinition of unused 'Series' from line 176
##[error]doc/source/development/contributing_docstring.rst(958,9): error F821: undefined name 'Substitution'
##[error]doc/source/development/contributing_docstring.rst(959,9): error F821: undefined name 'Appender'
##[error]doc/source/development/contributing_docstring.rst(965,9): error F821: undefined name 'Substitution'
##[error]doc/source/development/contributing_docstring.rst(966,9): error F821: undefined name 'Appender'
##[error]doc/source/development/contributing_docstring.rst(995,5): error F821: undefined name 'Appender'
##[error]doc/source/development/contributing_docstring.rst(995,14): error F821: undefined name 'template'
##[error]doc/source/development/contributing_docstring.rst(995,25): error F821: undefined name '_shared_doc_kwargs'
```

**Comment by jreback** [comment]
@mroeschke and this is after a merge master right?

**Comment by mroeschke** [comment]
Correct this is after the merge.

**Comment by jreback** [comment]
ok, let's just merge for now then and come back and see can make all green at some opoint.

**Pull request merged**
