### PR TITLE
Bump minimum version of Numba to 0.46.0

### PR DESCRIPTION
**Pull request by mroeschke**

### CODE REVIEW

**Comment by mroeschke** [comment]
I keep getting this error. Maybe it's a Windows OS issue based on which job failed?

```
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

**Comment by jreback** [comment]
> I keep getting this error. Maybe it's a Windows OS issue based on which job failed?
> 
> ```
> ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
> ```

that is a pretty old build
likely can’t pin numba there

**Comment by mroeschke** [comment]
Got it. Not a big deal if we can't make 0.46.0 the default version. Closing.

**Comment by jreback** [comment]
confused why can’t u add numba w/o requiring a version?

**Comment by jreback** [comment]
that build uses numpy 1.15 which is pretty old

**Pull request closed without merging**
